### PR TITLE
Update French 07/04/2020

### PR DESCRIPTION
**Pull request by bubuleur**
Hello I changed some words and noticed 3 untranslated words
https://zupimages.net/up/20/15/bxkg.jpg
Is it possible to translate these 3 words in the next update ? 
Thank you

### CODE REVIEW

**Comment by farindk** [comment]
Thank you. I have merged it and reverted the changes to '#éléments restants'.

**Comment by bubuleur** [comment]
Thank you very much

**Comment by bubuleur** [comment]
thin it is possible to add the words as in the photo?

**Comment by farindk** [comment]
I have added the words in the photo now. canvas="toile", I assume. The other one (base sizes), I do not know.
There are now also two new error messages.

**Comment by farindk** [comment]
Sorry, it is only one new error message. French is now even more complete than German :-)

**Comment by bubuleur** [comment]
Yeah, that's good. (Toile) and (Tailles de base)
merci :-)

**Comment by farindk** [comment]
And is this correct?
Cannot import image because the current directory is not valid.
->
Impossible d'importer l'image car le répertoire actuel n'est pas valide.

**Comment by bubuleur** [comment]
Yes it's correct

**Comment by farindk** [comment]
Merci beaucoup! Then French is complete for now!
I will publish a new beta-version today and it will be included in the v3.1.0 due next week.

**Comment by bubuleur** [comment]
Thank you so much you're very professional it's great 
I'll look at the beta version and I'll tell you if it's good by email
Nice day

**Pull request merged**
