### PR TITLE
Update strings-fr.po

### PR DESCRIPTION
**Pull request by bubuleur**

### CODE REVIEW

**Comment by bubuleur** [comment]
Hello, 
I saw that you released version 3. 0. 5 but you didn't add this new update
Heartily

**Comment by farindk** [comment]
Hello,

yes, because I had to make a time-critical release and didn't have time to
look into this yet.
Now, I just looked at your pull request. Thanks for that.
Only question I have is again with the "restante" vs. "déposée". Isn't that
the wrong way?
I mean, the number shown that number of images that still have to be
processed. Not the
number of images that are already finished.

Dirk


Am Mi., 15. Apr. 2020 um 08:13 Uhr schrieb bubuleur <
notifications@github.com>:

**Comment by bubuleur** [comment]
Okay, thanks for your answer.
Actually yes I have trouble with the words (restant) sorry for that but ok I see better do it is to say how much there is still image in the application ? 
I guess it's not possible but is it possible to release another update just for these changes ? 
Happy evening 
Heartily

**Comment by farindk** [comment]
Thanks. I cannot do a complete release because of these small changes. But the changes are now integrated and will be part of the next update. Maybe early next week.

**Comment by bubuleur** [comment]
Okay, thank you very much.
Kind regards

**Pull request merged**
